//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class il_ilce
    {
        public long id { get; set; }
        public byte plaka { get; set; }
        public string bolge { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
    }
}
