//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PoliklinikEntities5 : DbContext
    {
        public PoliklinikEntities5()
            : base("name=PoliklinikEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<il_ilce> il_ilce { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UrunAltAltAltKategori> UrunAltAltAltKategori { get; set; }
        public virtual DbSet<UrunAltAltKategori> UrunAltAltKategori { get; set; }
        public virtual DbSet<UrunAltKategori> UrunAltKategori { get; set; }
        public virtual DbSet<UrunDetayOzellikleri> UrunDetayOzellikleri { get; set; }
        public virtual DbSet<UrunKategori> UrunKategori { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunOzellikleri> UrunOzellikleri { get; set; }
        public virtual DbSet<Kargolar> Kargolar { get; set; }
        public virtual DbSet<Taksitlendirme> Taksitlendirme { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
    
        public virtual ObjectResult<sp_MetinAra_Result> sp_MetinAra(string metin)
        {
            var metinParameter = metin != null ?
                new ObjectParameter("Metin", metin) :
                new ObjectParameter("Metin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MetinAra_Result>("sp_MetinAra", metinParameter);
        }
    }
}
