//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public long ID { get; set; }
        public string KullaniciAdi { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.Guid> UrunID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunSiparisAdet { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
        public Nullable<decimal> ToplamFiyat { get; set; }
        public string UrunResmi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
    }
}
