//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public long ID { get; set; }
        public System.Guid SiparisNo { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public string KullaniciAdi { get; set; }
        public System.Guid UrunID1 { get; set; }
        public Nullable<System.Guid> UrunID2 { get; set; }
        public Nullable<System.Guid> UrunID3 { get; set; }
        public Nullable<System.Guid> UrunID4 { get; set; }
        public Nullable<System.Guid> UrunID5 { get; set; }
        public Nullable<System.Guid> UrunID6 { get; set; }
        public Nullable<System.Guid> UrunID7 { get; set; }
        public Nullable<System.Guid> UrunID8 { get; set; }
        public Nullable<System.Guid> UrunID9 { get; set; }
        public Nullable<System.Guid> UrunID10 { get; set; }
        public string UrunID1_Adi { get; set; }
        public string UrunID2_Adi { get; set; }
        public string UrunID3_Adi { get; set; }
        public string UrunID4_Adi { get; set; }
        public string UrunID5_Adi { get; set; }
        public string UrunID6_Adi { get; set; }
        public string UrunID7_Adi { get; set; }
        public string UrunID8_Adi { get; set; }
        public string UrunID9_Adi { get; set; }
        public string UrunID10_Adi { get; set; }
        public Nullable<byte> UrunID1_Adet { get; set; }
        public Nullable<byte> UrunID2_Adet { get; set; }
        public Nullable<byte> UrunID3_Adet { get; set; }
        public Nullable<byte> UrunID4_Adet { get; set; }
        public Nullable<byte> UrunID5_Adet { get; set; }
        public Nullable<byte> UrunID6_Adet { get; set; }
        public Nullable<byte> UrunID7_Adet { get; set; }
        public Nullable<byte> UrunID8_Adet { get; set; }
        public Nullable<byte> UrunID9_Adet { get; set; }
        public Nullable<byte> UrunID10_Adet { get; set; }
        public Nullable<decimal> UrunID1_Fiyat { get; set; }
        public Nullable<decimal> UrunID2_Fiyat { get; set; }
        public Nullable<decimal> UrunID3_Fiyat { get; set; }
        public Nullable<decimal> UrunID4_Fiyat { get; set; }
        public Nullable<decimal> UrunID5_Fiyat { get; set; }
        public Nullable<decimal> UrunID6_Fiyat { get; set; }
        public Nullable<decimal> UrunID7_Fiyat { get; set; }
        public Nullable<decimal> UrunID8_Fiyat { get; set; }
        public Nullable<decimal> UrunID9_Fiyat { get; set; }
        public Nullable<decimal> UrunID10_Fiyat { get; set; }
        public string Kargo_Adi { get; set; }
        public string KartNo { get; set; }
        public string Taksit_Adet { get; set; }
        public Nullable<decimal> ToplamFiyat { get; set; }
    }
}
