//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunAltKategori
    {
        public UrunAltKategori()
        {
            this.UrunAltAltKategori = new HashSet<UrunAltAltKategori>();
            this.Urunler = new HashSet<Urunler>();
            this.UrunOzellikleri = new HashSet<UrunOzellikleri>();
        }
    
        public long AltKategoriID { get; set; }
        public long AnaKategori { get; set; }
        public string Adi { get; set; }
        public System.Guid RowGuid { get; set; }
        public System.DateTime GuncellemeTarihi { get; set; }
    
        public virtual ICollection<UrunAltAltKategori> UrunAltAltKategori { get; set; }
        public virtual UrunKategori UrunKategori { get; set; }
        public virtual ICollection<Urunler> Urunler { get; set; }
        public virtual ICollection<UrunOzellikleri> UrunOzellikleri { get; set; }
    }
}
